# Generated by Django 5.2.15 on 2026-06-20 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Footer Column',
                'verbose_name_plural': 'Footer Columns',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='Join Our Newsletter', max_length=200)),
                ('subtext', models.TextField(blank=True)),
                ('button_label', models.CharField(default='Subscribe', max_length=50)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='cms/newsletter/')),
            ],
            options={
                'verbose_name': 'Newsletter Section',
                'verbose_name_plural': 'Newsletter Section',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Gravestone Memorials', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='cms/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='cms/')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
                ('copyright_text', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp'), ('twitter', 'Twitter / X'), ('linkedin', 'LinkedIn')], max_length=30)),
                ('url', models.URLField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='cms/social/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='cms.footercolumn')),
            ],
            options={
                'verbose_name': 'Footer Link',
                'verbose_name_plural': 'Footer Links',
                'ordering': ['order'],
            },
        ),
    ]
