# Generated by Django 5.2.15 on 2026-06-25 09:52

import core.fields
import json
from django.db import migrations


def str_to_json(apps, schema_editor):
    """Convert existing plain string values to {"en": value, "zh_hans": "", "zh_hant": ""}."""

    def wrap(value):
        if not value:
            return {"en": "", "zh_hans": "", "zh_hant": ""}
        try:
            parsed = json.loads(value)
            if isinstance(parsed, dict):
                return parsed
        except (json.JSONDecodeError, TypeError):
            pass
        return {"en": str(value), "zh_hans": "", "zh_hant": ""}

    SiteSettings = apps.get_model("cms", "SiteSettings")
    for obj in SiteSettings.objects.all():
        obj.copyright_text = json.dumps(wrap(obj.copyright_text))
        obj.save(update_fields=["copyright_text"])

    FooterColumn = apps.get_model("cms", "FooterColumn")
    for obj in FooterColumn.objects.all():
        obj.title = json.dumps(wrap(obj.title))
        obj.save(update_fields=["title"])

    FooterLink = apps.get_model("cms", "FooterLink")
    for obj in FooterLink.objects.all():
        obj.label = json.dumps(wrap(obj.label))
        obj.save(update_fields=["label"])

    NewsletterSection = apps.get_model("cms", "NewsletterSection")
    for obj in NewsletterSection.objects.all():
        obj.headline = json.dumps(wrap(obj.headline))
        obj.subtext = json.dumps(wrap(obj.subtext))
        obj.button_label = json.dumps(wrap(obj.button_label))
        obj.save(update_fields=["headline", "subtext", "button_label"])


def json_to_str(apps, schema_editor):
    """Reverse: extract English value back to a plain string."""

    def unwrap(value):
        try:
            parsed = json.loads(value)
            if isinstance(parsed, dict):
                return parsed.get("en", "")
        except (json.JSONDecodeError, TypeError):
            pass
        return value or ""

    SiteSettings = apps.get_model("cms", "SiteSettings")
    for obj in SiteSettings.objects.all():
        obj.copyright_text = unwrap(obj.copyright_text)
        obj.save(update_fields=["copyright_text"])

    FooterColumn = apps.get_model("cms", "FooterColumn")
    for obj in FooterColumn.objects.all():
        obj.title = unwrap(obj.title)
        obj.save(update_fields=["title"])

    FooterLink = apps.get_model("cms", "FooterLink")
    for obj in FooterLink.objects.all():
        obj.label = unwrap(obj.label)
        obj.save(update_fields=["label"])

    NewsletterSection = apps.get_model("cms", "NewsletterSection")
    for obj in NewsletterSection.objects.all():
        obj.headline = unwrap(obj.headline)
        obj.subtext = unwrap(obj.subtext)
        obj.button_label = unwrap(obj.button_label)
        obj.save(update_fields=["headline", "subtext", "button_label"])


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        # Step 1: convert existing string data to JSON text before changing field type
        migrations.RunPython(str_to_json, reverse_code=json_to_str),

        # Step 2: alter field types to JSONField (TranslatedField)
        migrations.AlterField(
            model_name='footercolumn',
            name='title',
            field=core.fields.TranslatedField(),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='label',
            field=core.fields.TranslatedField(),
        ),
        migrations.AlterField(
            model_name='newslettersection',
            name='button_label',
            field=core.fields.TranslatedField(),
        ),
        migrations.AlterField(
            model_name='newslettersection',
            name='headline',
            field=core.fields.TranslatedField(),
        ),
        migrations.AlterField(
            model_name='newslettersection',
            name='subtext',
            field=core.fields.TranslatedField(long_text=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='copyright_text',
            field=core.fields.TranslatedField(),
        ),
    ]