# Generated by Django 5.2.15 on 2026-06-25 09:52

import core.fields
import json
from django.db import migrations, models

# All home models and their text fields that need converting
CONVERSIONS = {
    "AboutUsSection":       ["body_text", "headline"],
    "FAQ":                  ["answer", "question"],
    "FAQSection":           ["headline"],
    "FeaturedProduct":      ["description", "name"],
    "HeroSection":          ["cta1_label", "cta2_label", "headline", "subtext"],
    "HowItWorksHeading":    ["headline", "subtext"],
    "HowItWorksStep":       ["description", "title"],
    "ProductsSectionHeading": ["headline", "subtext"],
    "ServicesSectionHeading": ["headline", "subtext"],
    "ServiceStep":          ["description", "title"],
    "StoneGallerySection":  ["explore_more_label", "headline", "subtext"],
    "Testimonial":          ["review_text"],
    "TestimonialsSection":  ["headline", "subtext"],
}


def wrap(value):
    if not value:
        return {"en": "", "zh_hans": "", "zh_hant": ""}
    try:
        parsed = json.loads(value)
        if isinstance(parsed, dict):
            return parsed
    except (json.JSONDecodeError, TypeError):
        pass
    return {"en": str(value), "zh_hans": "", "zh_hant": ""}


def unwrap(value):
    try:
        parsed = json.loads(value)
        if isinstance(parsed, dict):
            return parsed.get("en", "")
    except (json.JSONDecodeError, TypeError):
        pass
    return value or ""


def str_to_json(apps, schema_editor):
    for model_name, fields in CONVERSIONS.items():
        Model = apps.get_model("home", model_name)
        for obj in Model.objects.all():
            for field in fields:
                setattr(obj, field, json.dumps(wrap(getattr(obj, field))))
            obj.save(update_fields=fields)


def json_to_str(apps, schema_editor):
    for model_name, fields in CONVERSIONS.items():
        Model = apps.get_model("home", model_name)
        for obj in Model.objects.all():
            for field in fields:
                setattr(obj, field, unwrap(getattr(obj, field)))
            obj.save(update_fields=fields)


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        # Step 1: convert existing string data to JSON text before changing field type
        migrations.RunPython(str_to_json, reverse_code=json_to_str),

        # Step 2: alter all fields to TranslatedField (JSONField)
        migrations.AlterField(
            model_name='aboutussection',
            name='body_text',
            field=core.fields.TranslatedField(long_text=True),
        ),
        migrations.AlterField(
            model_name='aboutussection',
            name='headline',
            field=core.fields.TranslatedField(),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=core.fields.TranslatedField(long_text=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=core.fields.TranslatedField(),
        ),
        migrations.AlterField(
            model_name='faqsection',
            name='headline',
            field=core.fields.TranslatedField(),
        ),
        migrations.AlterField(
            model_name='featuredproduct',
            name='description',
            field=core.fields.TranslatedField(long_text=True),
        ),
        migrations.AlterField(
            model_name='featuredproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home/products/'),
        ),
        migrations.AlterField(
            model_name='featuredproduct',
            name='name',
            field=core.fields.TranslatedField(),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='cta1_label',
            field=core.fields.TranslatedField(verbose_name='CTA 1 Label'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='cta2_label',
            field=core.fields.TranslatedField(verbose_name='CTA 2 Label'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='headline',
            field=core.fields.TranslatedField(),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='subtext',
            field=core.fields.TranslatedField(long_text=True),
        ),
        migrations.AlterField(
            model_name='howitworksheading',
            name='headline',
            field=core.fields.TranslatedField(),
        ),
        migrations.AlterField(
            model_name='howitworksheading',
            name='subtext',
            field=core.fields.TranslatedField(),
        ),
        migrations.AlterField(
            model_name='howitworksstep',
            name='description',
            field=core.fields.TranslatedField(long_text=True),
        ),
        migrations.AlterField(
            model_name='howitworksstep',
            name='title',
            field=core.fields.TranslatedField(),
        ),
        migrations.AlterField(
            model_name='productssectionheading',
            name='headline',
            field=core.fields.TranslatedField(),
        ),
        migrations.AlterField(
            model_name='productssectionheading',
            name='subtext',
            field=core.fields.TranslatedField(),
        ),
        migrations.AlterField(
            model_name='servicessectionheading',
            name='headline',
            field=core.fields.TranslatedField(),
        ),
        migrations.AlterField(
            model_name='servicessectionheading',
            name='subtext',
            field=core.fields.TranslatedField(),
        ),
        migrations.AlterField(
            model_name='servicestep',
            name='description',
            field=core.fields.TranslatedField(long_text=True),
        ),
        migrations.AlterField(
            model_name='servicestep',
            name='title',
            field=core.fields.TranslatedField(),
        ),
        migrations.AlterField(
            model_name='stonegallerysection',
            name='explore_more_label',
            field=core.fields.TranslatedField(),
        ),
        migrations.AlterField(
            model_name='stonegallerysection',
            name='headline',
            field=core.fields.TranslatedField(),
        ),
        migrations.AlterField(
            model_name='stonegallerysection',
            name='subtext',
            field=core.fields.TranslatedField(),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='review_text',
            field=core.fields.TranslatedField(long_text=True),
        ),
        migrations.AlterField(
            model_name='testimonialssection',
            name='headline',
            field=core.fields.TranslatedField(),
        ),
        migrations.AlterField(
            model_name='testimonialssection',
            name='subtext',
            field=core.fields.TranslatedField(),
        ),
    ]