# Generated by Django 5.2.15 on 2026-06-26 12:23

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurWorkPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', core.fields.TranslatedField()),
                ('subtitle', core.fields.TranslatedField()),
            ],
            options={
                'verbose_name': 'Our Work Page',
                'verbose_name_plural': 'Our Work Page',
            },
        ),
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', core.fields.TranslatedField()),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Work Category',
                'verbose_name_plural': 'Work Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', core.fields.TranslatedField()),
                ('image', models.ImageField(upload_to='portfolio/work/')),
                ('description', core.fields.TranslatedField(long_text=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='portfolio.workcategory')),
            ],
            options={
                'verbose_name': 'Work Item',
                'verbose_name_plural': 'Work Items',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
